development:
  adapter: postgresql
  database: numerology_dev
  pool: 5
  host: localhost
  username: <%= ENV["APP_POSTGRES_USER"] %>
  password: <%= ENV["APP_POSTGRES_PASSWORD"] %>

test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: <%= ENV["APP_POSTGRES_USER"] %>
  password: <%= ENV["APP_POSTGRES_PASSWORD"] %>
