development:
  adapter: postgresql
  database: numerology_dev
  pool: 5
  host: localhost
  username: ruby
  password: 123456789
    
test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: ruby
  password: 123456789